// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_AltMenuScreenMZ","status":true,"description":"メインメニュー画面をシンプルにします。","parameters":{"actorCols":"0"}},
{"name":"MNKR_AltBattleStatusMZ","status":true,"description":"戦闘中のステータスウィンドウをシンプルにします。","parameters":{"actorAutoCols":"true"}},
{"name":"MNKR_AltSkillMenuMZ","status":true,"description":"メインメニュー内スキル画面をシンプルにします。","parameters":{"gaugeWidth":"352"}},
{"name":"MNKR_SyncPlayerStep","status":true,"description":"プレイヤーとフォロワーの足踏みアニメを同期します。","parameters":{}}
];
