// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DrawChatAtMenu","status":false,"description":"メニューで顔グラフィックの代わりに歩行グラフィックを表示","parameters":{}},
{"name":"NaiveBattleStatus","status":false,"description":"非常にシンプルな戦闘ステータス表示","parameters":{}},
{"name":"MNKR_AltMenuScreenMZ","status":true,"description":"メインメニュー画面をシンプルにします。","parameters":{"actorCols":"0"}},
{"name":"MNKR_AltBattleStatusMZ","status":true,"description":"戦闘中のステータスウィンドウをシンプルにします。","parameters":{"actorAutoCols":"true"}},
{"name":"MNKR_AltSkillMenuMZ","status":true,"description":"メインメニュー内スキル画面をシンプルにします。","parameters":{"gaugeWidth":"352"}}
];
